name: train-deepspeed-transformers-docker
on:
  push:
    branches:
    - dkmiller/ghcr
  schedule:
    - cron: "0 0/2 * * *"
  pull_request:
    branches:
      - main
      # TODO: remove me.
      - dkmiller/ghcr
    paths:
      - workflows/train/deepspeed/transformers/**
      - .github/workflows/train-deepspeed-transformers-docker.yml

# https://docs.github.com/en/actions/guides/publishing-docker-images

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: docker build
      run: |
        docker build . --tag docker.pkg.github.com/deepspeed/transformers
      working-directory: workflows/train/deepspeed/transformers
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: docker.pkg.github.com/deepspeed/transformers
        tag_with_ref: true

# docker build workflows/train/deepspeed/transformers/ -t train-deepspeed-transformers

#      - name: Push to GitHub Packages
#        uses: docker/build-push-action@v1
#        with:
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#          registry: docker.pkg.github.com
#          repository: my-org/my-repo/my-image
#          tag_with_ref: true
