name: train-deepspeed-transformers-docker
on:
  # TODO: remove this one.
  push:
    branches:
    - dkmiller/ghcr
  # TODO: run only every two weeks.
  schedule:
    - cron: "0 0/2 * * *"
  pull_request:
    branches:
      - main
    paths:
      - workflows/train/deepspeed/transformers/dockerfile
      - .github/workflows/train-deepspeed-transformers-docker.yml

# https://docs.github.com/en/actions/guides/publishing-docker-images

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: docker build
      run: |
        docker build . --tag docker.pkg.github.com/deepspeed/transformers
      working-directory: workflows/train/deepspeed/transformers
    # TODO: add an `if` condition so this only runs on the main branch.
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: docker.pkg.github.com/deepspeed/transformers
        tag_with_ref: true
