name: tutorial-using-cli
on:
  schedule:
    - cron: "0 */2 * * *"
  pull_request:
    branches:
      - main
    paths:
      - experimental/using-cli/**
      - .github/workflows/tutorial-using-cli.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    #- name: setup python
    #  uses: actions/setup-python@v2
    #  with: 
    #    python-version: "3.8"
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_CLI_CREDS}}
    - name: install the new ml extension
      run: az extension add --source https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2/ml-0.0.63-py3-none-any.whl --pip-extra-index-urls https://azuremlsdktestpypi.azureedge.net/sdk-cli-v2 -y
    - name: run lightgbm-iris.sh
      run: bash lightgbm-iris.sh > ./logs.txt
      working-directory: experimental/using-cli
    - name: upload logs 
      uses: actions/upload-artifacts@v2
      with:
        name: logs
        path: ./logs.txt
      working-directory: experimental/using-cli